#ifndef TLC_CORE_CONFIG_HPP
#define TLC_CORE_CONFIG_HPP

#cmakedefine TLC_CONFIG_BUILD_TESTS
#cmakedefine TLC_CONFIG_BUILD_EXAMPLES
#cmakedefine TLC_CONFIG_BUILD_DEBUG
#cmakedefine TLC_CONFIG_ENABLE_LOGGING
#define TLC_CONFIG_VERSION_MAJOR @tlc_VERSION_MAJOR@
#define TLC_CONFIG_VERSION_MINOR @tlc_VERSION_MINOR@
#define TLC_CONFIG_VERSION_LLVM @TLC_CONFIG_VERSION_LLVM@

#endif // TLC_CORE_CONFIG_HPP
