include(GNUInstallDirs)

set(TLC_CONFIG_AS_SUBPROJECT OFF)
if (CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
  set(TLC_CONFIG_AS_SUBPROJECT ON)
endif ()

set(TLC_CONFIG_BUILD_DEBUG OFF)
if (CMAKE_BUILD_TYPE STREQUAL Debug)
  set(TLC_CONFIG_BUILD_DEBUG ON)
endif ()

set(TLC_CONFIG_BUILD_EXAMPLES ON)
set(TLC_CONFIG_BUILD_TESTS ON)
set(TLC_CONFIG_VERSION_LLVM 17)
